language: java
jdk:
  - openjdk8

branches: # 어느 브랜치가 푸시될 때 수행할지 지정한다. 현재는 오직 mastre 브랜치에 push될 떄만 수행한다.
  only:
    - master

# Travis CI 서버의 Home2
cache:   # gradle을 통해 의존성을 받게 되면 이를 해당 디렉토리에 캐시하여, 같은 의존성은 다음 배포 떄부터 다시 받지 않도록 설정한다.
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'


before_install:  # 모든 사용자한테 gradlew에 대한 접근권한을 풀어준다.
  - chmod +x gradlew

script: "./gradlew clean build"  # master 브랜치에 push 순간 수행 할 명령어. 프로젝트 내부에 둔 gradlew을 통해 clean & build를 수행

# CI 실행 완료시 자동으로 메일로 알람
notifications:
  email:
    recipients:
      - dmyun23@gmail.com