language: java
jdk:
  - openjdk8

branches: # 어느 브랜치가 푸시될 때 수행할지 지정한다. 현재는 오직 mastre 브랜치에 push될 떄만 수행한다.
  only:
    - master

# Travis CI 서버의 Home2
cache:   # gradle을 통해 의존성을 받게 되면 이를 해당 디렉토리에 캐시하여, 같은 의존성은 다음 배포 떄부터 다시 받지 않도록 설정한다.
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'


#before_install:
#  - chmod +x gradlew
#
#before_deploy:
#  - mkdir -p before-deploy # zip에 포함시킬 파일들을 담을 디렉토리 생성 중
#  - cp scripts/*.sh before-deploy/
#  - cp appspec.yml before-deploy/
#  - cp build/libs/*.jar before-deploy/
#  - cd before-deploy && zip -r before-deploy *
#  - cd ../ && mkdir -p deploy
#  - mv before-deploy/before-deploy.zip deploy/freelec-springboot2-webservice.zip

#deploy:
#  - provider: s3
#    access_key_id: $AWS_ACCESS_KEY
#    secret_access_key: $AWS_SECRET_KEY
#    bucket: freelec-springboot-build-space
#    region: ap-northeast-2
#    skip_cleanup: true
#    acl: private # zip 파일접근을 private으로
#    local_dir: deploy # before_deploy에서 생성한 디렉토리
#    wait-until-deployed: true
#
#  - provider: codedeploy
#    access_key_id: $AWS_ACCESS_KEY
#    secret_access_key: $AWS_SECRET_KEY
#    bucket: freelec-springboot-build-space
#    key : freelec-springboot2-webservice.zip
#    bundle-type: zip
#    application: freelec-springboot2-webservice
#    deployment-group: freelec-springboot2-webservice-group
#    region: ap-northeast-2
#    wait-until-deployed: true

script: "./gradlew clean build"  # master 브랜치에 push 순간 수행 할 명령어. 프로젝트 내부에 둔 gradlew을 통해 clean & build를 수행

# CI 실행 완료시 자동으로 메일로 알람
notifications:
  email:
    recipients:
      - dmyun23@gmail.com